apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: operationbearhug
  annotations: {}
  generation: 1
  labels:
    app: deployment-operationbearhug-blog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deployment-operationbearhug-blog
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app: deployment-operationbearhug-blog
    spec:
      containers:
        - env:
            - name: mail__options__service
              value: Mailgun
            - name: mail__transport
              value: SMTP
            - name: url
              value: https://operationbearhug.ca/updates
          envFrom:
            - secretRef:
                name: blog-secret
          image: ghost:alpine
          imagePullPolicy: Always
          name: blog
          ports:
            - containerPort: 2368
              name: tcp2368
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: "2.0Gi"
            requests:
              cpu: "350m"
              memory: "200Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: operationbearhug-ghost-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: operationbearhug-ghost-pvc
          persistentVolumeClaim:
            claimName: operationbearhug-ghost-pvc
