apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operationbearhug-ghost-pvc
  namespace: operationbearhug
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
