apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: operationbearhug
  annotations: {}
  labels: {}
spec:
  ports:
    - name: tcp80
      port: 2368
      protocol: TCP
      targetPort: 2368
  selector:
    app: deployment-operationbearhug-blog
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
