apiVersion: batch/v1
kind: CronJob
metadata:
  name: freedom-pg-db-backup
  namespace: operationbearhug
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: avencera/postgres-s3-backup
              envFrom:
                - secretRef:
                    name: s3-secret
                - secretRef:
                    name: pg-secret
          restartPolicy: Never
