apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freedom-postgres
  namespace: avencera
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
