apiVersion: batch/v1
kind: Job
metadata:
  name: restore-db
  namespace: operationbearhug
spec:
  template:
    spec:
      containers:
        - name: restore-db
          image: operationbearhug/postgres-s3-restore
          envFrom:
            - secretRef:
                name: s3-secret
            - secretRef:
                name: pg-secret
      restartPolicy: Never
  backoffLimit: 4
