apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: operationbearhug.ca
  namespace: operationbearhug
spec:
  secretName: operationbearhug-ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.operationbearhug.ca"
  dnsNames:
    - operationbearhug.ca
    - "*.operationbearhug.ca"
