apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freedom-operationbearhug-ca
  namespace: operationbearhug
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 12m
spec:
  tls:
    - hosts:
        - operationbearhug.ca
      secretName: operationbearhug-ca-tls
  rules:
    - host: operationbearhug.ca
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: freedom
                port:
                  number: 2384
